services:
  bot:
    tty: true
    build:
      context: .
    
    container_name: mr_python
    volumes:
      - type: bind
        source: .
        target: /app
    
    command: python src/app.py