services:
  bot:
    tty: true
    build:
      context: .
      dockerfile : docker/Dockerfile
    
    env_file:
      - .env 
    container_name: mr_python
    volumes:
      - type: bind
        source: .
        target: /app
    
    command: python src/app.py